### ISSUE TITLE
New version for Scala 2.12.11

### ISSUE THREAD

**Issue by jozic** [sksamuel/scapegoat#316] opened 2020-03-17 17:54 UTC
Would be nice to get this cross-published for newly released Scala 2.12.11. Pretty please

**Comment by sksamuel** [comment] 2020-03-21 22:03
1.4.2 released for all versions.

**Comment by jozic** [comment] 2020-03-27 01:35
Doesn't look like 2.12.11 made it to `all versions`
![image](https://user-images.githubusercontent.com/124249/77712258-abc21180-6fa9-11ea-8fc3-72d6cceee092.png)

**Comment by mccartney** [comment] 2020-03-27 05:17
I confirm I see the same as you do at https://search.maven.org/search?q=g:com.sksamuel.scapegoat

@sksamuel did you release for 2.12.11?

**Comment by sksamuel** [comment] 2020-03-27 05:40
I did a full release so I thought.

**Comment by sksamuel** [comment] 2020-03-27 05:42
After the recent changes where do we specify the list of cross versions ?

**Comment by mwz** [comment] 2020-03-27 10:51
Since I removed travis config and the travis sbt plugin you need to manually release for each version - I know it's a pain and I'll try to automate all this in the next day or so.

**Comment by mccartney** [comment] 2020-03-27 10:53
I guess a simple shell script would be enough for now.

**Comment by jozic** [comment] 2020-04-07 15:43
hey folks, any help is needed to push this forward?

**Comment by mwz** [comment] 2020-04-08 21:58
We have a new release pipeline now, we should try it out 😉

**Comment by mccartney** [comment] 2020-04-09 19:39
OK. I am trying although I don't know if I am doing the right thing here.
I went to Releases, took the private Draft, named it `1.4.3` with `v1.4.3` tag and clicked Publish release.

**Comment by mccartney** [comment] 2020-04-09 19:40
Failed with 
```
 [info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = com.***.scapegoat
[info] Preparing a new staging repository for [sbt-sonatype] scalac-scapegoat-plugin 1.4.3
[info] Reading staging repository profiles...
[info] Reading staging profiles...
[info] No previous staging repository for [sbt-sonatype] scalac-scapegoat-plugin 1.4.3 was found
[error] java.lang.IllegalArgumentException: Profile com.***.scapegoat is not found. Check your sonatypeProfileName setting in build.sbt
[error] Use 'last' for the full log.
##[error]Process completed with exit cod
```

**Comment by mccartney** [comment] 2020-04-09 19:41
The triple asterisk (`***`) looks fishy

**Comment by mccartney** [comment] 2020-04-09 20:07
sbt-sonatypes says:
> sonatypeProfileName
> This is your Sonatype acount profile name, e.g. org.xerial. If you do not set this value, it will be the same with the organization value.

**Comment by mccartney** [comment] 2020-04-09 20:12
Trying https://github.com/sksamuel/scapegoat/commit/af19c8ad47b3e3856c12df8632cb42e8dcb6136e#diff-45ac75879221b921f35800b2421aa728

**Comment by mccartney** [comment] 2020-04-09 20:23
Didn't work, reverting.

**Comment by mccartney** [comment] 2020-04-09 20:35
Nah. After moving the tag it failed with:
```
- Your workflow file was invalid: The workflow is not valid. .github/workflows/master-release.yml (Line: 38, Col: 14): Unrecognized named-value: 'SONATYPE_USERNAME'. Located at position 1 within expression: SONATYPE_USERNAME
```

**Comment by mccartney** [comment] 2020-04-09 20:45
With fixing the variable name it fails with the previous message:
```
[error] java.lang.IllegalArgumentException: Profile com.***.scapegoat is not found. Check your sonatypeProfileName setting in build.sbt
```
Reverting the workflow change.
I guess we might try simply adding this variable to `build.sbt` (a bit unclean solution, but I guess it might work).

**Comment by mccartney** [comment] 2020-04-09 21:09
Now the changes seems to have taken effect, but they weren't good either:
```
[error] java.lang.IllegalArgumentException: Profile *** is not found. Check your sonatypeProfileName setting in build.sbt
```

**Comment by mccartney** [comment] 2020-04-09 21:15
Another guess is to specify the profile name to `com.sksamuel`, an idea inspired by https://issues.sonatype.org/browse/OSSRH-54525?focusedCommentId=896956&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-896956

**Comment by mccartney** [comment] 2020-04-09 21:24
And that worked!
Sam has event received an email ;)
> [info]      email: to:sam@***.com

Let's see if the versions have landed in Maven in a few hours.

**Comment by sksamuel** [comment] 2020-04-09 21:26
Those sonatype emails never ever get sent FYI. Not that it matters.

**Comment by mccartney** [comment] 2020-04-10 07:33
@jozic there it is
![image](https://user-images.githubusercontent.com/762437/78972526-3eb48d00-7b0e-11ea-8ea3-6614577881f8.png)

**Closed by mccartney** 2020-04-10 07:33 UTC

**Comment by mccartney** [comment] 2020-04-10 07:34
Also the need to specify sonatypeProfileName - I guess it's a bug in `sbt-release` - most likely due to incompatibility with what `sbt-sonatype` expects as input.

**Comment by sksamuel** [comment] 2020-04-10 11:52
Nice.

**Comment by mwz** [comment] 2020-04-12 15:12
Just catching up with this thread, well done @mccartney for fixing this.

> Also the need to specify sonatypeProfileName - I guess it's a bug in `sbt-release` - most likely due to incompatibility with what `sbt-sonatype` expects as input.

It's not a bug - you need to specify the profile name explicitly if it doesn't match the organisation name (`com.sksamuel.scapegoat` in this case). Sorry, it's something I missed - I didn't realise that Sam was using `com.sksamuel` as the profile, which obviously makes perfect sense now 😄
