### ISSUE TITLE
VariableShadowing false positive on variables named `_`

### ISSUE THREAD

**Issue by jabrouwer82** [sksamuel/scapegoat#398] opened 2020-06-30 22:05 UTC
In the following code, VariableShadowing emits a warning on line 5 (the second `_ <-` line).

```
for {
  a <- IO("a")
  _ <- IO(println("print something"))
  _ <- IO(println(a))
} yield a
```

Scapegoat should probably just ignore any variables names `_`.

scala 2.12.11
scapegoat 1.4.4

**Comment by jcallin** [comment] 2020-07-01 22:35
I've observed this happening in _all_ instances of chaining operators.
```
a
  .map(s => f(s))
  .map(s => g(s))
```
Produces the same error from Scapegoat

**Comment by mccartney** [comment] 2020-09-29 19:48
@jcallin I cannot reproduce using Scapegoat 1.4.6. I suspect this might got solved in #357 (released in 1.4.5).

**Comment by mccartney** [comment] 2020-09-29 21:17
Also @jabrouwer82 your case doesn't trigger a warning in Scapegoat 1.4.6 I am currently using. Or actually I am trying:
```
object Test {

  def irrelevant(how: Int): Seq[String] = Seq(s"irrelevant cats $how")

  for {
     a <- 1 to 5
     _ <- irrelevant(3)
     _ <- irrelevant(5)
  } yield a

}
```
as we don't have Cats in classpath of our source test base.

Would you be so kind to check your code against a newer Scapegoat and report back?

**Comment by jabrouwer82** [comment] 2020-10-05 19:10
I'm no longer at the company with that code/issue, so I can't confirm. The snippet you posted looks like the same thing though, so I think it's safe to assume this is fixed!

Thanks so much!

**Comment by mccartney** [comment] 2020-10-05 19:15
OK. Thanks for coming back.

I am gonna resolve in good faith. If we learn anything to the contrary, we are happy to re-open or deal with another similar issue.

**Closed by mccartney** 2020-10-05 19:15 UTC
Labels: false positive

**Comment by dmalpi** [comment] 2024-08-12 15:57
I know this is 4 year later, but I have exactly same issue with scapegoat 2.1.6.

**Comment by saeltz** [comment] 2024-08-12 18:18
Do you have some reproduction code for this issue?

**Comment by dmalpi** [comment] 2024-08-12 18:32
I edited my comment, do you need more info? 

Thanks in advance!

**Comment by dmalpi** [comment] 2024-08-19 09:31
I think if I edit the comment you didn't receive a notification. My bad.

In our case, all the false positives are raised when using `EitherT` from Cats package. For example:

 
``` scala
    for {
      _ <- EitherT.pure[Future, String](logger.info(s"something"))
      _ <- EitherT.pure[Future, String](logger.info(s"something"))
    } yield ()
```

But it is also raised when using non-cats code:

``` scala
    for {
      _ <- Right(logger.info(s"something"))
      _ <- Right(logger.info(s"something"))
    } yield ()
```

Also, doesn't matter if there are two subsequent lines or not:

``` scala
    for {
      _ <- Option(logger.info(s"something"))
      asd <- Option(logger.info(s"something"))
      _ <- Option(logger.info(s"$asd"))
    } yield ()
```

**Comment by saeltz** [comment] 2024-09-17 10:58
@dmalpi, I added a test for the case you reported in #871. It only seems to fail with Scala 2.12. Do you happen to be on that version?
